version: '3.8'

services:

  web_app:
    build: .
    container_name: web_app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15.8
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: